const fs = require('fs');

let products = [
  {
    "id": 101,
    "name": "صافولا",
    "nameEn": "Safola",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "صافولا",
    "country": "السعودية",
    "image": "",
    "reason": "منتجات صافولا تدعم جهات داعمة",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 102,
    "name": "عافية",
    "nameEn": "Afia",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "صافولا",
    "country": "السعودية",
    "image": "",
    "reason": "تابعة لصافولا",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 103,
    "name": "العربي",
    "nameEn": "Al Arabi",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "صافولا",
    "country": "السعودية",
    "image": "",
    "reason": "تابعة لصافولا",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 104,
    "name": "زهرتي",
    "nameEn": "Zahrati",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "صافولا",
    "country": "السعودية",
    "image": "",
    "reason": "تابعة لصافولا",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 105,
    "name": "شمس",
    "nameEn": "Shams",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "عافية العالمية",
    "country": "السعودية",
    "image": "",
    "reason": "تابعة لشركة عافية",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 106,
    "name": "دلال",
    "nameEn": "Dalal",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "عافية العالمية",
    "country": "السعودية",
    "image": "",
    "reason": "تابعة لشركة عافية",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 107,
    "name": "افكو",
    "nameEn": "Afco",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "افكو",
    "country": "مصر",
    "image": "",
    "reason": "منتجات افكو تدعم جهات داعمة",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 108,
    "name": "الشروق",
    "nameEn": "Al Shorouk",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "افكو",
    "country": "مصر",
    "image": "",
    "reason": "تابعة لافكو",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 109,
    "name": "حياة",
    "nameEn": "Hayat",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "افكو",
    "country": "مصر",
    "image": "",
    "reason": "تابعة لافكو",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 110,
    "name": "زيت الجميل",
    "nameEn": "Al Jameel",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "الجميل",
    "country": "السعودية",
    "image": "",
    "reason": "منتجات الجميل تدعم جهات داعمة",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 111,
    "name": "مازولا",
    "nameEn": "Mazola",
    "status": "مقاطعة",
    "cat": "زيت الطهي",
    "company": "ACH Food",
    "country": "أمريكا",
    "image": "",
    "reason": "منتج أمريكي",
    "alt": "الحلي، اطايب، جنان، امير، امينة، فورتن، سيرين، ابو زهرة، تالين، زينه، دلال، دايلي فريش، الدعيسي، مازا، فاتن، مرمريز، كرامي، النخبة",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 112,
    "name": "الحلي",
    "nameEn": "Al Heli",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "الحلي",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي 100%",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 113,
    "name": "اطايب",
    "nameEn": "Atayeb",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "اطايب",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 114,
    "name": "جنان",
    "nameEn": "Jinan",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "جنان",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 115,
    "name": "امير",
    "nameEn": "Ameer",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "امير",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 116,
    "name": "امينة",
    "nameEn": "Amina",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "امينة",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 117,
    "name": "فورتن",
    "nameEn": "Fortune",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "فورتن",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 118,
    "name": "سيرين",
    "nameEn": "Sereen",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "سيرين",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 119,
    "name": "ابو زهرة",
    "nameEn": "Abu Zahra",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "ابو زهرة",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 120,
    "name": "تالين",
    "nameEn": "Talin",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "تالين",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 121,
    "name": "زينه",
    "nameEn": "Zeina",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "زينه",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 122,
    "name": "دايلي فريش",
    "nameEn": "Daily Fresh",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "دايلي فريش",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 123,
    "name": "الدعيسي",
    "nameEn": "Al Da'aisi",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "الدعيسي",
    "country": "اليمن",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج يمني",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 124,
    "name": "مازا",
    "nameEn": "Maza",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "مازا",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 125,
    "name": "فاتن",
    "nameEn": "Faten",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "فاتن",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 126,
    "name": "مرمريز",
    "nameEn": "Marmariz",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "مرمريز",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 127,
    "name": "كرامي",
    "nameEn": "Karami",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "كرامي",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 128,
    "name": "النخبة",
    "nameEn": "Prime",
    "status": "بديل",
    "cat": "زيت الطهي",
    "company": "النخبة",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-23"
  },
  {
    "id": 201,
    "name": "اديداس",
    "nameEn": "Adidas",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Adidas",
    "country": "ألمانيا",
    "image": "",
    "reason": "شركة ألمانية داعمة",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 202,
    "name": "ريكسونا",
    "nameEn": "Rexona",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Unilever",
    "country": "بريطانيا/هولندا",
    "image": "",
    "reason": "منتجات يونيليفر",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 203,
    "name": "ليدي سبيد ستيك",
    "nameEn": "Lady Speed Stick",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Colgate-Palmolive",
    "country": "أمريكا",
    "image": "",
    "reason": "منتج أمريكي",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 204,
    "name": "آرم",
    "nameEn": "Arm & Hammer",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Church & Dwight",
    "country": "أمريكا",
    "image": "",
    "reason": "منتج أمريكي",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 205,
    "name": "نيفيا",
    "nameEn": "Nivea",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Beiersdorf",
    "country": "ألمانيا",
    "image": "",
    "reason": "شركة ألمانية",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 206,
    "name": "هيميلايا",
    "nameEn": "Himalaya",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Himalaya",
    "country": "الهند",
    "image": "",
    "reason": "منتج هندي داعم",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 207,
    "name": "فا",
    "nameEn": "Fa",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Henkel",
    "country": "ألمانيا",
    "image": "",
    "reason": "شركة ألمانية",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 208,
    "name": "دوف",
    "nameEn": "Dove",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Unilever",
    "country": "بريطانيا/هولندا",
    "image": "",
    "reason": "منتجات يونيليفر",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 209,
    "name": "آكس",
    "nameEn": "Axe",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Unilever",
    "country": "بريطانيا/هولندا",
    "image": "",
    "reason": "منتجات يونيليفر",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 210,
    "name": "آولد سبايس",
    "nameEn": "Old Spice",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Procter & Gamble",
    "country": "أمريكا",
    "image": "",
    "reason": "منتج أمريكي",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 211,
    "name": "امالفي",
    "nameEn": "Amalfi",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "Amalfi",
    "country": "إيطاليا",
    "image": "",
    "reason": "منتج أوروبي",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 212,
    "name": "ام يو ام",
    "nameEn": "MUM",
    "status": "مقاطعة",
    "cat": "مزيلات عرق",
    "company": "MUM",
    "country": "أمريكا",
    "image": "",
    "reason": "منتج أمريكي",
    "alt": "هايجين، ديب سينس، ماي، هيفين فلاور، بيزليين، سكون",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 213,
    "name": "هايجين",
    "nameEn": "Hygiene",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "هايجين",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 214,
    "name": "ديب سينس",
    "nameEn": "Deep Sense",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "ديب سينس",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 215,
    "name": "ماي",
    "nameEn": "My",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "ماي",
    "country": "إيران",
    "image": "",
    "reason": "بديل إيراني",
    "alt": "منتج إيراني",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 216,
    "name": "هيفين فلاور",
    "nameEn": "Heaven Flower",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "هيفين فلاور",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 217,
    "name": "بيزليين",
    "nameEn": "Bisline",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "بيزليين",
    "country": "السعودية",
    "image": "",
    "reason": "بديل محلي ممتاز",
    "alt": "منتج سعودي",
    "updatedAt": "2025-06-03"
  },
  {
    "id": 218,
    "name": "سكون",
    "nameEn": "Schon",
    "status": "بديل",
    "cat": "مزيلات عرق",
    "company": "سكون",
    "country": "إيران",
    "image": "",
    "reason": "بديل إيراني",
    "alt": "منتج إيراني",
    "updatedAt": "2025-06-03"
  }
]
let keywords = [
  {id:"kw1", name:"الدعم المادي المباشر", desc:"الشركات التي تقدم دعماً مالياً مباشراً للكيان الصهيوني أو للمستوطنات أو للجيش الإسرائيلي."},
  {id:"kw2", name:"الدعم المعنوي والتعاطف", desc:"الشركات التي تعلن تعاطفها أو دعمها المعنوي للكيان الصهيوني عبر بيانات أو تصريحات رسمية."},
  {id:"kw3", name:"دعم المثلية والشواذ", desc:"الشركات التي تدعم منظمات المثلية أو تروج للأفكار الشاذة المخالفة للفطرة."},
  {id:"kw4", name:"شهادات الكوشير", desc:"المنتجات الحاصلة على شهادة كوشير (Kosher) تعني أنها معتمدة حسب الشريعة اليهودية، وتدعم اقتصاد الكيان عبر الرسوم والتراخيص."},
  {id:"kw5", name:"التصدير للكيان", desc:"الشركات التي تصدر منتجاتها إلى الكيان الصهيوني، مما يدعم اقتصاده."},
  {id:"kw6", name:"مقاطعة دولة", desc:"المقاطعة بناءً على موقف الدولة الداعم للكيان الصهيوني."},
  {id:"kw7", name:"الاستثمارات التي تتجاوز 3%", desc:"الشركات التي لديها استثمارات في الكيان الصهيوني تتجاوز 3% من رأسمالها."},
  {id:"kw8", name:"التصنيع داخل الأراضي المحتلة", desc:"الشركات التي تملك مصانع أو فروعاً داخل المستوطنات غير الشرعية."},
  {id:"kw9", name:"الشركات التعاونية (التوأمة)", desc:"الشركات التي لديها اتفاقيات توأمة أو تعاون مع كيانات صهيونية."}
];

let categories = [
  {id:"cat1", name:"زيت الطهي", color:"#e8a040"},
  {id:"cat2", name:"مزيلات عرق", color:"#d4a373"},
  {id:"cat3", name:"اجهزة كهربائية", color:"#708090"},
  {id:"cat4", name:"دجاج", color:"#f5deb3"},
  {id:"cat5", name:"ألبان", color:"#f5f5dc"},
  {id:"cat6", name:"صابون غسيل ملابس", color:"#87ceeb"},
  {id:"cat7", name:"تلفزيونات", color:"#483d8b"},
  {id:"cat8", name:"سائل جلي", color:"#ffb6c1"},
  {id:"cat9", name:"منظفات ارضية", color:"#9acd32"},
  {id:"cat10", name:"حلويات", color:"#e8a040"},
  {id:"cat11", name:"هواتف", color:"#2e8b57"}
];

let countries = [
  {id:"cnt1", nameAr:"السعودية", nameEn:"Saudi Arabia"},
  {id:"cnt2", nameAr:"الإمارات", nameEn:"UAE"},
  {id:"cnt3", nameAr:"الكويت", nameEn:"Kuwait"},
  {id:"cnt4", nameAr:"قطر", nameEn:"Qatar"},
  {id:"cnt5", nameAr:"البحرين", nameEn:"Bahrain"},
  {id:"cnt6", nameAr:"عمان", nameEn:"Oman"},
  {id:"cnt7", nameAr:"مصر", nameEn:"Egypt"},
  {id:"cnt8", nameAr:"الأردن", nameEn:"Jordan"},
  {id:"cnt9", nameAr:"فلسطين", nameEn:"Palestine"},
  {id:"cnt10", nameAr:"العراق", nameEn:"Iraq"},
  {id:"cnt11", nameAr:"سوريا", nameEn:"Syria"},
  {id:"cnt12", nameAr:"لبنان", nameEn:"Lebanon"},
  {id:"cnt13", nameAr:"اليمن", nameEn:"Yemen"},
  {id:"cnt14", nameAr:"ليبيا", nameEn:"Libya"},
  {id:"cnt15", nameAr:"تونس", nameEn:"Tunisia"},
  {id:"cnt16", nameAr:"الجزائر", nameEn:"Algeria"},
  {id:"cnt17", nameAr:"المغرب", nameEn:"Morocco"},
  {id:"cnt18", nameAr:"السودان", nameEn:"Sudan"},
  {id:"cnt19", nameAr:"تركيا", nameEn:"Turkey"},
  {id:"cnt20", nameAr:"إيران", nameEn:"Iran"},
  {id:"cnt21", nameAr:"باكستان", nameEn:"Pakistan"},
  {id:"cnt22", nameAr:"الهند", nameEn:"India"},
  {id:"cnt23", nameAr:"الصين", nameEn:"China"},
  {id:"cnt24", nameAr:"اليابان", nameEn:"Japan"},
  {id:"cnt25", nameAr:"كوريا الجنوبية", nameEn:"South Korea"},
  {id:"cnt26", nameAr:"أمريكا", nameEn:"USA"},
  {id:"cnt27", nameAr:"بريطانيا", nameEn:"UK"},
  {id:"cnt28", nameAr:"فرنسا", nameEn:"France"},
  {id:"cnt29", nameAr:"ألمانيا", nameEn:"Germany"},
  {id:"cnt30", nameAr:"إيطاليا", nameEn:"Italy"},
  {id:"cnt31", nameAr:"إسبانيا", nameEn:"Spain"},
  {id:"cnt32", nameAr:"روسيا", nameEn:"Russia"},
  {id:"cnt33", nameAr:"كندا", nameEn:"Canada"},
  {id:"cnt34", nameAr:"أستراليا", nameEn:"Australia"},
  {id:"cnt35", nameAr:"البرازيل", nameEn:"Brazil"},
];

let companiesList = [
  {id:"comp1", name:"صافولا", nameEn:"Safola", parent:""},
  {id:"comp2", name:"عافية", nameEn:"Afia", parent:"صافولا"},
  {id:"comp3", name:"افكو", nameEn:"Afco", parent:""},
  {id:"comp4", name:"الحلي", nameEn:"Al Heli", parent:""},
  {id:"comp5", name:"اطايب", nameEn:"Atayeb", parent:""},
  {id:"comp6", name:"جنان", nameEn:"Jinan", parent:""},
  {id:"comp7", name:"امير", nameEn:"Ameer", parent:""},
  {id:"comp8", name:"امينة", nameEn:"Amina", parent:""},
  {id:"comp9", name:"فورتن", nameEn:"Fortune", parent:""},
  {id:"comp10", name:"سيرين", nameEn:"Sereen", parent:""},
  {id:"comp11", name:"ابو زهرة", nameEn:"Abu Zahra", parent:""},
  {id:"comp12", name:"تالين", nameEn:"Talin", parent:""},
  {id:"comp13", name:"زينه", nameEn:"Zeina", parent:""},
  {id:"comp14", name:"دايلي فريش", nameEn:"Daily Fresh", parent:""},
  {id:"comp15", name:"الدعيسي", nameEn:"Al Da'aisi", parent:""},
  {id:"comp16", name:"مازا", nameEn:"Maza", parent:""},
  {id:"comp17", name:"فاتن", nameEn:"Faten", parent:""},
  {id:"comp18", name:"مرمريز", nameEn:"Marmariz", parent:""},
  {id:"comp19", name:"كرامي", nameEn:"Karami", parent:""},
  {id:"comp20", name:"النخبة", nameEn:"Prime", parent:""},
  {id:"comp21", name:"اديداس", nameEn:"Adidas", parent:""},
  {id:"comp22", name:"Unilever", nameEn:"Unilever", parent:""},
  {id:"comp23", name:"هايجين", nameEn:"Hygiene", parent:""},
  {id:"comp24", name:"ديب سينس", nameEn:"Deep Sense", parent:""},
  {id:"comp25", name:"LG", nameEn:"LG", parent:""},
  {id:"comp26", name:"سامسونج", nameEn:"Samsung", parent:""},
  {id:"comp27", name:"كسترون", nameEn:"Kastron", parent:""},
  {id:"comp28", name:"زينت", nameEn:"Zenet", parent:""},
  {id:"comp29", name:"امريكانا", nameEn:"Americana", parent:""},
  {id:"comp30", name:"المزرعة", nameEn:"Al Mazraa", parent:""},
  {id:"comp31", name:"الزعيم", nameEn:"Al Zaeem", parent:""},
  {id:"comp32", name:"نستله", nameEn:"Nestlé", parent:""},
  {id:"comp33", name:"أوال", nameEn:"Awal", parent:""},
  {id:"comp34", name:"النور", nameEn:"Al Noor", parent:""},
  {id:"comp35", name:"ندى", nameEn:"Nada", parent:""},
  {id:"comp36", name:"العملاق", nameEn:"Al Amlaq", parent:""},
  {id:"comp37", name:"ديكسن", nameEn:"Dickson", parent:""},
  {id:"comp38", name:"وينيكس", nameEn:"Winix", parent:""},
  {id:"comp39", name:"P&G", nameEn:"P&G", parent:""},
  {id:"comp40", name:"Apple", nameEn:"Apple", parent:""},
];
                                       

let normalized = products.map((product)=>{
    for(let category of categories){
        if(product.cat == category.name){
            product.category_id = category.id.substring(3);
            break;
        }
    }

    for(let country of countries){
        if(product.country == country.nameAr){
            product.country_id = country.id.substring(3);
            break;
        }
    }

    for(let company of companiesList){
        if(product.company == company.name){
            product.company_id = company.id.substring(4);
            break;
        }
    }

    if(product.status == 'بديل') {
        product.status_id = 1;
    } else {
        product.status_id = 2;

    }

    return product;
});
const jsonString = JSON.stringify(normalized, null, 2);
fs.writeFileSync('products.json', jsonString);
// const normalized = [...new Set(products.map(p => p.status))];
console.log(normalized);